"""Source selection invariants and optional integration with pinned cloc."""
import importlib.util
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("measure", ROOT / "scripts/measure_source_sizes.py")
measure = importlib.util.module_from_spec(spec)
spec.loader.exec_module(measure)
POLICY = json.loads((ROOT / "scripts/source_size_policy.json").read_text(encoding="utf-8"))


class SelectionTests(unittest.TestCase):
    def test_tests_examples_and_benchmarks_are_included(self):
        for path in ("tests/test_parser.py", "examples/demo.ts", "benchmarks/main.go"):
            self.assertIsNone(measure.path_exclusion(path, POLICY))

    def test_known_dependency_and_generated_paths_are_excluded(self):
        for path in ("ui/node_modules/x/index.js", "vendor/a.go", "docs/demo.py", "src/a_pb2.py", "src/app.min.js", "vite.config.ts"):
            self.assertIsNotNone(measure.path_exclusion(path, POLICY))
        self.assertIsNone(measure.path_exclusion("src/vendor_adapter.py", POLICY))

    def test_manifest_hash_survives_transport_but_binds_membership(self):
        rows = [{"entry_ids": ["entry-1"], "commit": "abc", "repo_url": "https://example.com/r"}]
        transported = json.loads(json.dumps(rows, indent=2).replace("\n", "\r\n"))
        self.assertEqual(measure.manifest_content_sha256(rows), measure.manifest_content_sha256(transported))
        transported[0]["entry_ids"].append("entry-2")
        self.assertNotEqual(measure.manifest_content_sha256(rows), measure.manifest_content_sha256(transported))


@unittest.skipUnless(os.environ.get("CLOC_SCRIPT") and shutil.which("git"), "Set CLOC_SCRIPT to run pinned-cloc integration")
class ClocIntegrationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        contents = {
            "src/main.py": "# comment\n\nx = 1\n",
            "tests/duplicate.py": "# comment\n\nx = 1\n",
            "examples/demo.js": "// comment\nconst x = 1;\n",
            "vendor/vendor.py": "x = 1\n",
            "docs/demo.py": "x = 1\n",
            "src/generated.py": "# Code generated by fixture. DO NOT EDIT\nx = 1\n",
            "src/marked.py": "x = 1\n",
            "settings.json": '{"a": 1}\n',
            ".gitattributes": "src/marked.py linguist-vendored=true\n",
        }
        for name, text in contents.items():
            path = self.root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode())
        self.git("init", "-q")
        self.git("config", "core.autocrlf", "false")
        self.git("add", ".")
        self.git("-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "commit", "-qm", "fixture")
        self.row = {"repo_url": "https://example.com/fixture", "commit": self.git("rev-parse", "HEAD").strip(), "batch_id": "fixture", "entry_ids": ["entry-1"]}
        self.command = [os.environ.get("CLOC_PERL", "perl"), os.environ["CLOC_SCRIPT"]]

    def git(self, *args):
        return subprocess.check_output(["git", "-C", str(self.root), *args], text=True, stderr=subprocess.PIPE)

    def test_real_cloc_preserves_duplicate_paths_and_excludes_non_source(self):
        result = measure.measure(self.row, self.root, POLICY, self.command)
        self.assertEqual(result["sloc"], 3)
        self.assertEqual(result["source_files"], 3)
        self.assertEqual(result["languages"]["Python"]["code"], 2)
        self.assertEqual(result["languages"]["Python"]["comment"], 2)
        self.assertEqual(result["excluded_files_by_reason"]["generated_header"], 1)
        self.assertEqual(result["excluded_files_by_reason"]["git_generated_or_vendored_attribute"], 1)
        self.assertEqual(result["excluded_language_files"]["JSON"], 1)
        self.assertEqual(result, measure.measure(self.row, self.root, POLICY, self.command))

    def test_wrong_commit_and_modified_tracked_source_fail(self):
        with self.assertRaises(ValueError):
            measure.measure(dict(self.row, commit="wrong"), self.root, POLICY, self.command)
        (self.root / "src/main.py").write_text("x = 2\n", encoding="utf-8")
        with self.assertRaises(subprocess.CalledProcessError):
            measure.measure(self.row, self.root, POLICY, self.command)


if __name__ == "__main__":
    unittest.main()
